//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBoardTask3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductSold
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public int StoreId { get; set; }
        [DisplayName("DateSold")]
        public System.DateTime DateSold { get; set; }
        public string ReturnDateForDisplay
        {
            get
            {
                return this.DateSold.ToString("dd/mm/yyyy");
            }
        }

        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }

        public string CustomerName { get; internal set; }
        public string ProductName { get; internal set; }
        public string StoreName { get; internal set; }
    }
}
